# Generated by Django 2.2 on 2021-01-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_auto_20210118_1557'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
