# Generated by Django 2.2 on 2021-01-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_auto_20210118_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['title']},
        ),
    ]
